<a href="https://colab.research.google.com/github/Deepthi-Nadar/Data-Analytics-With-Python/blob/main/AI_Assisted_Python_Analysis_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

df = pd.read_csv("/content/Superstore.csv", encoding='latin1')

In [5]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [8]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [9]:
df.drop_duplicates(inplace=True)

df['Order Date'] = pd.to_datetime(df['Order Date'])

In [10]:
df['Year'] = df['Order Date'].dt.year

sales_by_category = df.groupby('Category')['Sales'].sum()

# Which product category generates the highest total sales?

In [13]:
highest_total_sales= df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

In [14]:
highest_total_sales

Category
Technology         836154.0330
Furniture          741999.7953
Office Supplies    719047.0320
Name: Sales, dtype: float64

# Which sub-category is the least profitable despite high sales?

In [19]:
subcat_analysis = df.groupby("Sub-Category")[["Sales", "Profit"]].sum()

In [20]:
print(subcat_analysis.sort_values(by="Sales", ascending=False))

                    Sales      Profit
Sub-Category
Phones        330007.0540  44515.7306
Chairs        328449.1030  26590.1663
Storage       223843.6080  21278.8264
Tables        206965.5320 -17725.4811
Binders       203412.7330  30221.7633
Machines      189238.6310   3384.7569
Accessories   167380.3180  41936.6357
Copiers       149528.0300  55617.8249
Bookcases     114879.9963  -3472.5560
Appliances    107532.1610  18138.0054
Furnishings    91705.1640  13059.1436
Paper          78479.2060  34053.5693
Supplies       46673.5380  -1189.0995
Art            27118.7920   6527.7870
Envelopes      16476.4020   6964.1767
Labels         12486.3120   5546.2540
Fasteners       3024.2800    949.5182

# 3. Which region contributes the highest profit?

In [21]:
re_highest_pro=df.groupby("Region")["Profit"].sum().sort_values(ascending=False)

In [23]:
print(re_highest_pro)

Region
West       108418.4489
East        91522.7800
South       46749.4303
Central     39706.3625
Name: Profit, dtype: float64

# 4. Which states are generating losses?

In [24]:
State_losses=df.groupby("State")["Profit"].sum()

In [25]:
loss_states=State_losses[State_losses<0]

In [26]:
print(loss_states)

State
Arizona           -3427.9246
Colorado          -6527.8579
Florida           -3399.3017
Illinois         -12607.8870
North Carolina    -7490.9122
Ohio             -16971.3766
Oregon            -1190.4705
Pennsylvania     -15559.9603
Tennessee         -5341.6936
Texas            -25729.3563
Name: Profit, dtype: float64

# 5. Which customer segment generates the highest average order value?

In [27]:
highest_average_order_value = df.groupby("Segment")["Sales"].mean().sort_values(ascending=False)

In [28]:
print(highest_average_order_value)

Segment
Home Office    240.972041
Corporate      233.823300
Consumer       223.733644
Name: Sales, dtype: float64

# **Discount & Profit Analysis**

# 6. Does giving higher discounts reduce profit?

In [39]:
reduce_profit=df.groupby("Discount")["Profit"].mean().sort_values(ascending=False)

In [40]:
print(reduce_profit)

Discount
0.10     96.055074
0.00     66.900292
0.15     27.288298
0.20     24.702572
0.60    -43.077212
0.30    -45.679636
0.32    -88.560656
0.70    -95.874060
0.80   -101.796797
0.40   -111.927429
0.45   -226.646464
0.50   -310.703456
Name: Profit, dtype: float64

# 8. Which products receive high discounts but still perform poorly?

In [46]:
product_analysis = df.groupby("Product Name")[["Discount", "Profit"]].sum()

print(product_analysis.head())

                                                    Discount    Profit
Product Name
"While you Were Out" Message Book, One Form per...       0.4   10.3880
#10 Gummed Flap White Envelopes, 100/Box                 0.4   16.7678
#10 Self-Seal White Envelopes                            0.2   52.1230
#10 White Business Envelopes,4 1/8 x 9 1/2               0.4  223.1408
#10- 4 1/8" x 9 1/2" Recycled Envelopes                  0.8  115.2806

In [47]:
print(product_analysis.sort_values(by="Profit"))

                                                    Discount      Profit
Product Name
Cubify CubeX 3D Printer Double Head Print               1.60  -8879.9704
Lexmark MX611dhe Monochrome Laser Printer               1.60  -4589.9730
Cubify CubeX 3D Printer Triple Head Print               0.50  -3839.9904
Chromcraft Bull-Nose Wood Oval Conference Table...      1.40  -2876.1156
Bush Advantage Collection Racetrack Conference ...      2.45  -1934.3976
...                                                      ...         ...
HP Designjet T520 Inkjet Large Format Printer -...      0.50   4094.9766
Canon PC1060 Personal Laser Copier                      0.60   4570.9347
Hewlett Packard LaserJet 3310 Copier                    1.60   6983.8836
Fellowes PB500 Electric Punch Plastic Comb Bind...      2.40   7753.0390
Canon imageCLASS 2200 Advanced Copier                   0.60  25199.9280

[1850 rows x 2 columns]

# Which month had the highest sales?

In [50]:
df["Month"] = df["Order Date"].dt.month_name()

In [51]:
monthly_sales = df.groupby("Month")["Sales"].sum()

print(monthly_sales.sort_values(ascending=False))

Month
November     352461.0710
December     325293.5035
September    307649.9457
March        205005.4888
October      200322.9847
August       159044.0630
May          155028.8117
June         152718.6793
July         147238.0970
April        137762.1286
January       94924.8356
February      59751.2514
Name: Sales, dtype: float64

10. Which year showed the highest business growth?

In [52]:
df["Year"] = df["Order Date"].dt.year

In [53]:
yearly_sales = df.groupby("Year")["Sales"].sum()

print(yearly_sales)

Year
2014    484247.4981
2015    470532.5090
2016    609205.5980
2017    733215.2552
Name: Sales, dtype: float64